version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: hackathon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
