-- 黑客松立项评审系统 建表脚本
CREATE DATABASE IF NOT EXISTS hackathon DEFAULT CHARACTER SET utf8mb4;

USE hackathon;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  tech_stack TEXT,
  team_size INT DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_reviewers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  reviewer_id BIGINT UNSIGNED NOT NULL,
  UNIQUE KEY uk_project_reviewer (project_id, reviewer_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  reviewer_id BIGINT UNSIGNED NOT NULL,
  innovation INT NOT NULL DEFAULT 0,
  technology INT NOT NULL DEFAULT 0,
  value INT NOT NULL DEFAULT 0,
  comment TEXT,
  conclusion VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 内置管理员账号（密码：admin123）
INSERT IGNORE INTO users (email, password_hash, role) VALUES
('admin@hackathon.com', '$2a$10$8K1p/a0dL1LXMIgoEDFrwOfMQVZsVvR7H1zU5x7Y9Yf0mN0kU4Y6y', 'admin');
